"""Tests for T2: seeded GameRNG wrapper + determinism invariant.

Given / When / Then is structured per test for clarity.
The frozen SHA256 hash in ``test_determinism_invariant_frozen_hash`` locks
the RNG contract: any change to the underlying generation algorithm forces
an intentional, visible update to this literal.
"""

from __future__ import annotations

import hashlib
from typing import TypeVar

from htop_tycoon.engine.rng import GameRNG

T = TypeVar("T")


# Frozen expected SHA256 hex digest of 1000 floats from GameRNG(42).
# Generated by hashing repr([rng.float() for _ in range(1000)]) for a fresh
# GameRNG(42). Verified stable across three consecutive invocations on
# Python 3.12.10 / macOS aarch64. DO NOT update without an explicit plan
# change + a recorded rationale in .omo/evidence/.
FROZEN_DETERMINISM_HASH = (
    "ffbd4eb3aa80bf7f841ab00cfef84600e55de637ae9b5353b9d5d29cf544a777"
)


class TestGameRNGConstruction:
    """GameRNG constructs and exposes only the documented surface."""

    def test_construct_with_seed(self) -> None:
        """Given: a seed value
        When: GameRNG(seed) is instantiated
        Then: a GameRNG instance is returned without error
        """
        rng = GameRNG(42)
        assert isinstance(rng, GameRNG)

    def test_does_not_expose_random_attribute(self) -> None:
        """Given: a GameRNG instance
        When: attribute access is attempted
        Then: there is no public 'random' attribute on the instance
        """
        rng = GameRNG(42)
        assert not hasattr(rng, "random"), (
            "GameRNG must not expose the underlying random.Random publicly"
        )


class TestGameRNGFloat:
    """rng.float() returns deterministic floats in [0.0, 1.0)."""

    def test_float_in_unit_interval(self) -> None:
        """Given: a GameRNG instance
        When: float() is called many times
        Then: every returned value is in [0.0, 1.0)
        """
        rng = GameRNG(7)
        for _ in range(1000):
            value = rng.float()
            assert 0.0 <= value < 1.0


class TestGameRNGInt:
    """rng.int(lo, hi) returns integers in the inclusive [lo, hi] range."""

    def test_int_in_range(self) -> None:
        """Given: a GameRNG instance with bounds
        When: int(lo, hi) is called many times
        Then: every returned value is in [lo, hi] inclusive
        """
        rng = GameRNG(7)
        lo, hi = 3, 9
        for _ in range(1000):
            value = rng.int(lo, hi)
            assert isinstance(value, int)
            assert lo <= value <= hi


class TestGameRNGChoice:
    """rng.choice(seq) returns an element from the sequence."""

    def test_choice_returns_element(self) -> None:
        """Given: a non-empty sequence
        When: choice(seq) is called
        Then: the returned value is an element of seq
        """
        rng = GameRNG(7)
        seq = ("alpha", "beta", "gamma", "delta")
        for _ in range(200):
            pick = rng.choice(seq)
            assert pick in seq

    def test_choice_covers_sequence(self) -> None:
        """Given: a small sequence
        When: choice(seq) is called many times
        Then: every element is selected at least once (RNG touches all)
        """
        rng = GameRNG(7)
        seq = ("a", "b", "c", "d")
        seen = {rng.choice(seq) for _ in range(500)}
        assert seen == set(seq)


class TestGameRNGWeightedChoice:
    """rng.weighted_choice(seq, weights) honours the supplied weights."""

    def test_weighted_choice_respects_weights(self) -> None:
        """Given: a sequence with very biased weights
        When: weighted_choice is called many times
        Then: the high-weight element dominates within a small tolerance
        """
        rng = GameRNG(7)
        seq = ("rare", "common")
        weights = (0.1, 0.9)
        trials = 5000
        counts = {"rare": 0, "common": 0}
        for _ in range(trials):
            counts[rng.weighted_choice(seq, weights)] += 1
        # Expected: 500 rare, 4500 common. Allow ±5pp slack on each.
        rare_ratio = counts["rare"] / trials
        common_ratio = counts["common"] / trials
        assert 0.05 <= rare_ratio <= 0.15, (
            f"rare_ratio={rare_ratio:.3f} outside [0.05, 0.15]"
        )
        assert 0.85 <= common_ratio <= 0.95, (
            f"common_ratio={common_ratio:.3f} outside [0.85, 0.95]"
        )


class TestGameRNGEvent:
    """rng.event(p) returns True approximately p fraction of the time."""

    def test_event_frequency_within_tolerance(self) -> None:
        """Given: a fixed probability
        When: event(p) is called many times
        Then: the empirical frequency is within ±5% of p
        """
        rng = GameRNG(7)
        p = 0.3
        trials = 10000
        true_count = sum(1 for _ in range(trials) if rng.event(p))
        observed = true_count / trials
        assert abs(observed - p) <= 0.05, (
            f"observed={observed:.4f} outside p±0.05 (true_count={true_count})"
        )


class TestGameRNGDeterminism:
    """Same seed reproduces the same sequence; different seeds diverge."""

    def test_same_seed_same_float_sequence(self) -> None:
        """Given: two GameRNG instances built with the same seed
        When: both produce a sequence of floats
        Then: the two sequences are identical
        """
        a = GameRNG(42)
        b = GameRNG(42)
        seq_a = [a.float() for _ in range(500)]
        seq_b = [b.float() for _ in range(500)]
        assert seq_a == seq_b

    def test_different_seeds_diverge(self) -> None:
        """Given: two GameRNG instances with different seeds
        When: both produce a sequence of floats
        Then: the sequences are not identical
        """
        a = GameRNG(1)
        b = GameRNG(2)
        seq_a = [a.float() for _ in range(200)]
        seq_b = [b.float() for _ in range(200)]
        assert seq_a != seq_b

    def test_determinism_invariant_frozen_hash(self) -> None:
        """Given: GameRNG(42)
        When: 1000 consecutive float() calls are SHA256-hashed
        Then: the hash equals the frozen expected value
        """
        rng = GameRNG(42)
        values: list[float] = [rng.float() for _ in range(1000)]
        digest = hashlib.sha256(repr(values).encode("utf-8")).hexdigest()
        assert digest == FROZEN_DETERMINISM_HASH, (
            f"Determinism invariant broken. actual={digest} "
            f"expected={FROZEN_DETERMINISM_HASH}"
        )


class TestGameRNGTypeStubs:
    """API surface matches the typed signatures in the spec."""

    def test_returns_python_types(self) -> None:
        """Given: a GameRNG instance
        When: each method is called with valid arguments
        Then: concrete runtime types are bool / int / float / str (element type)
        """
        rng = GameRNG(42)
        assert isinstance(rng.float(), float)
        assert isinstance(rng.int(0, 10), int)
        pick: str = rng.choice(("a", "b", "c"))
        assert isinstance(pick, str)
        assert isinstance(rng.event(0.5), bool)
