"""Domain models for htop-tycoon (T4+)."""

from __future__ import annotations

from htop_tycoon.domain.ending import (
    ALL_ENDINGS,
    BANKRUPTCY,
    HOSTILE_MA,
    IPO,
    SECRET,
    VOLUNTARY_SALE,
    EndingCondition,
    EndingType,
    EvaluationContext,
)
from htop_tycoon.domain.event import (
    AddEmployee,
    BoostRevenue,
    Choice,
    Effect,
    Event,
    EventCondition,
    RemoveEmployee,
    ScheduleEnding,
    ScheduleNextEvent,
    ShiftMarketShare,
    StoryNode,
    StoryOnChoose,
    TriggerSecretInvestor,
)
from htop_tycoon.domain.state import (
    Company,
    CompetitorId,
    DepartmentId,
    EmployeeId,
    EventId,
    GameState,
    GameTime,
    ProductId,
    StoryNodeId,
    new_game,
    state_hash,
)

__all__ = [
    "ALL_ENDINGS",
    "AddEmployee",
    "BANKRUPTCY",
    "BoostRevenue",
    "Choice",
    "Company",
    "CompetitorId",
    "DepartmentId",
    "Effect",
    "EmployeeId",
    "EndingCondition",
    "EndingType",
    "Event",
    "EventCondition",
    "EventId",
    "EvaluationContext",
    "GameState",
    "GameTime",
    "HOSTILE_MA",
    "IPO",
    "ProductId",
    "RemoveEmployee",
    "SECRET",
    "ScheduleEnding",
    "ScheduleNextEvent",
    "ShiftMarketShare",
    "StoryNode",
    "StoryNodeId",
    "StoryOnChoose",
    "TriggerSecretInvestor",
    "VOLUNTARY_SALE",
    "new_game",
    "state_hash",
]
